<a href="https://colab.research.google.com/github/JakeOh/202504_itwill_oracle88/blob/main/python19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 필요한 패키지(모듈) import

In [1]:
import pandas as pd
import seaborn as sns

# tips 데이터 셋

In [2]:
# seaborn 패키지의 tips 예제 데이터 셋을 로드
tips = sns.load_dataset('tips')

In [3]:
print(type(tips))

<class 'pandas.core.frame.DataFrame'>

In [4]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# 연습문제

*   DataFrame의 row, column 개수
*   DataFrame의 컬럼 이름
*   DataFrame에서 첫 5개 row 출력
*   DataFrmae에서 마지막 5개 row 출력
*   DataFrame의 요약 정보 출력
*   DataFrame에서 숫자 타입 변수들의 기술 통계량 출력
*   DataFrame에서 카테고리 타입 변수들의 빈도수 출력
*   total_bill 컬럼의 값이 최댓값인 행을 출력
*   total_bill 컬럼의 값이 최솟값인 행을 출력
*   남성(sex)들의 팁(tip)의 평균 출력
*   여성(sex)들의 팁(tip)의 평균 출력
*   일요일(day)의 팁(tip)의 평균 출력
*   일요일(day), 남성(sex)의 팁(tip)의 평균 출력
*   일요일(day), 여성(sex)의 팁(tip)의 평균 출력

## DataFrame의 row, column 개수

In [5]:
tips.shape  # (행의 갯수, 열의 갯수) tuple

(244, 7)

In [6]:
print('rows =', tips.shape[0])
print('columns =', tips.shape[1])

rows = 244
columns = 7

## DataFrame의 컬럼 이름

In [7]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [8]:
# DF의 columns 속성은 for-in 구문에서 사용할 수 있음.
for col in tips.columns:
    print(col)

total_bill
tip
sex
smoker
day
time
size

## DataFrame에서 첫 5개 row 출력

In [9]:
tips.iloc[:5]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
tips.loc[:4]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## DataFrmae에서 마지막 5개 row 출력

In [12]:
tips.iloc[-5:]

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [18]:
tips.loc[239:]
# tips.loc[(tips.shape[0] - 5):]

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [23]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

## DataFrame의 요약 정보 출력

In [24]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

## DataFrame에서 숫자 타입 변수들의 기술 통계량 출력

In [25]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

## DataFrame에서 카테고리 타입 변수들의 빈도수 출력

In [26]:
tips['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [27]:
tips.smoker.value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [28]:
tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [29]:
tips['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

정수 타입 변수(컬럼)도 경우에 따라서는 범주(카테고리) 타입 변수일 수 있다.

## total_bill 컬럼의 값이 최댓값인 행을 출력

In [32]:
tips.total_bill.max()

50.81

In [33]:
tips[tips.total_bill == 50.81]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [34]:
tips[tips.total_bill == tips.total_bill.max()]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

## total_bill 컬럼의 값이 최솟값인 행을 출력

In [35]:
tips[tips.total_bill == tips.total_bill.min()]

    total_bill  tip     sex smoker  day    time  size
67        3.07  1.0  Female    Yes  Sat  Dinner     1

## 남성(sex)들의 팁(tip)의 평균 출력

In [37]:
# 성별이 남성인 레코드만으로 만들어진 DF
male_df = tips[tips.sex == 'Male']

In [38]:
male_df

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [39]:
male_df.tip.mean()

np.float64(3.0896178343949043)

## 여성(sex)들의 팁(tip)의 평균 출력

In [40]:
female_df = tips[tips.sex == 'Female']

In [41]:
female_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [42]:
female_df.tip.mean()

np.float64(2.8334482758620685)

## 일요일(day)의 팁(tip)의 평균 출력

In [43]:
tips.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [44]:
sunday_df = tips[tips.day == 'Sun']

In [45]:
sunday_df

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [46]:
sunday_df.tip.mean()

np.float64(3.2551315789473687)

요일별 팁의 평균을 모두 출력하세요.

In [50]:
# Series.values 속성: Series에 저장된 모든 값들.
tips.day.values

['Sun', 'Sun', 'Sun', 'Sun', 'Sun', ..., 'Sat', 'Sat', 'Sat', 'Sat', 'Thur']
Length: 244
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [48]:
# Series.unique(): Series에서 중복되지 않는 값들.
tips.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [52]:
print(tips[tips.day == 'Sun'].tip.mean())
print(tips[tips.day == 'Sat'].tip.mean())
print(tips[tips.day == 'Thur'].tip.mean())
print(tips[tips.day == 'Fri'].tip.mean())

3.2551315789473687
2.993103448275862
2.771451612903225
2.7347368421052627

In [54]:
for d in tips.day.unique():
    subset_df = tips[tips.day == d]
    tip_mean = subset_df.tip.mean()
    print(f'{d}: {tip_mean}')

Sun: 3.2551315789473687
Sat: 2.993103448275862
Thur: 2.771451612903225
Fri: 2.7347368421052627

## 일요일(day), 남성(sex)의 팁(tip)의 평균 출력

In [55]:
sunday_male_df = tips[(tips.day == 'Sun') & (tips.sex == 'Male')]

In [57]:
sunday_male_df.head()

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2

In [58]:
sunday_male_df.shape

(58, 7)

In [59]:
sunday_male_df.tip.mean()

np.float64(3.2203448275862065)

## 일요일(day), 여성(sex)의 팁(tip)의 평균 출력

In [60]:
sunday_female_df = tips[(tips.day == 'Sun') & (tips.sex == 'Female')]

In [61]:
sunday_female_df.head()

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [62]:
sunday_female_df.shape

(18, 7)

In [63]:
sunday_female_df.tip.mean()

np.float64(3.3672222222222223)

## 식사 시간(Lunch, Dinner) 별 팁의 평균

In [67]:
tips.time.value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [68]:
tips.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [70]:
for t in tips.time.unique():
    subset_df = tips[tips.time == t]
    tip_mean = subset_df.tip.mean()
    print(f'{t}: {tip_mean}')

Dinner: 3.102670454545454
Lunch: 2.728088235294118

# titanic 데이터 셋

In [71]:
titanic = sns.load_dataset('titanic')

In [72]:
print(type(titanic))

<class 'pandas.core.frame.DataFrame'>

In [73]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

titanic 데이터프레임 컬럼 설명:
*   survived: 생존 여부(0=사망, 1=생존)
    *   alive 컬럼과 같은 내용(no=사망, yes=생존)
*   pclass: 객실 등급
    *   class 컬럼과 같은 내용(1=First, 2=Second, ...)
*   sex: 성별(male/female)
*   who: 성인남성(man), 성인여성(woman), 어린이(child)
*   age: 나이
*   sibsp: 동행한 형제자매 또는 배우자의 수
*   parch: 동행한 부모 또는 자녀의 수
*   fare: 탑승권 가격. 운임.
*   adult_male: 성인 남성인 지 여부
*   alone: 혼자 탑승했는 지 여부

In [74]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [76]:
titanic.head(n=7)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

NaN: Not a Number(숫자 아님). 숫자 타입 컬럼에 값이 없는 경우.

In [77]:
titanic.tail(n=7)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
884,0,3,male,25.0,0,0,7.050,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.125,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.450,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.750,Q,Third,man,True,NaN,Queenstown,no,True

## 범주(카테고리) 타입 변수(컬럼) 분석

In [78]:
titanic.survived.value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [79]:
titanic.alive.value_counts()

alive
no     549
yes    342
Name: count, dtype: int64

In [80]:
titanic.sex.value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [81]:
titanic.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

## 생존자 비율

*   전체 승객 중 남성 생존자 비율, 여성 생존자 비율
    *   남성 생존자 비율 = (남성 생존자 수) / (전체 승객 수)
    *   여성 생존자 비율 = (여성 생존자 수) / (전체 승객 수)

*   생존자들 중 남성 생존자 비율, 여성 생존자 비율
    *   남성 생존자 비율 = (남성 생존자 수) / (전체 생존자 수)
    *   여성 생존자 비율 = (여성 생존자 수) / (전체 생존자 수)

*   생존자들 중 성인 생존자 비율, 어린이 생존자 비율
    *   성인 생존자 비율 = (성인 생존자 수) / (전체 생존자 수)
    *   어린이 생존자 비율 = (어린이 생존자 수) / (전체 생존자 수)

In [83]:
# 전체 승객수
# num_of_total = titanic.shape[0]
num_of_total = len(titanic)
num_of_total

891

In [86]:
# 남성 생존자
num_of_male_alive = len(titanic[(titanic.sex == 'male') & (titanic.alive == 'yes')])
num_of_male_alive

109

In [87]:
# 여성 생존자
num_of_female_alive = len(titanic[(titanic.sex == 'female') & (titanic.alive == 'yes')])
num_of_female_alive

233

In [88]:
ratio_male_alive = num_of_male_alive / num_of_total
ratio_male_alive

0.122334455667789

In [89]:
ratio_female_alive = num_of_female_alive / num_of_total
ratio_female_alive

0.2615039281705948

In [91]:
# 전체 생존자
num_of_total_alive = len(titanic[titanic.alive == 'yes'])
num_of_total_alive

342

In [92]:
print('남성 생존자 비율 =', num_of_male_alive / num_of_total_alive)
print('여성 생존자 비율 =', num_of_female_alive / num_of_total_alive)

남성 생존자 비율 = 0.31871345029239767
여성 생존자 비율 = 0.6812865497076024

In [96]:
# 어린이 생존자
num_of_child_alive = len(titanic[(titanic.who == 'child') & (titanic.alive == 'yes')])
num_of_child_alive

49

In [98]:
# 성인 생존자
num_of_adult_alive = len(titanic[(titanic.who != 'child') & (titanic.alive == 'yes')])
num_of_adult_alive

293

In [99]:
print('성인 생존자 비율 =', num_of_adult_alive / num_of_total_alive)
print('어린이 생존자 비율 =', num_of_child_alive / num_of_total_alive)

성인 생존자 비율 = 0.8567251461988304
어린이 생존자 비율 = 0.14327485380116958

## 객실 등급별 생존자 비율

*   (1등급 객실 생존자 비율) = (1등급 객실 생존자 수) / (전체 생존자 수)
*   (2등급 객실 생존자 비율) = (2등급 객실 생존자 수) / (전체 생존자 수)
*   (3등급 객실 생존자 비율) = (3등급 객실 생존자 수) / (전체 생존자 수)

*   (1등급 객실 생존자 비율) = (1등급 객실 생존자 수) / (1등급 객실 승객수)
*   (2등급 객실 생존자 비율) = (2등급 객실 생존자 수) / (2등급 객실 승객수)
*   (3등급 객실 생존자 비율) = (3등급 객실 생존자 수) / (3등급 객실 승객수)